resolver: lts-20.22

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
- falsify-0.1.1
# TODO Use Hackage version when released
# - dahdit-0.4.0
- git: git@github.com:ejconlon/dahdit.git
  commit: 0dc1fa08418254a7ef21aaf5440e400b09e55289
- data-sword-0.2.0.3
